Repository singnyeo/nb02-seven-team2, pull requests merged in 2025-06, with the labels that each got.

#42 hotfix: 그룹 목록조회/상세조회 API static 메서드로 변경
  backend/app.js
  backend/controllers/group-controller.js
  backend/package-lock.json
  backend/package.json
Labels: 🐛 fix

#43 hotfix: 그룹 추천/추천취소 API static 메서드로 변경
  backend/controllers/group-controller.js
  backend/routes/groups.js
Labels: 🐛 fix

#52 hotfix : error-handler, groups, app 수정
  backend/app.js
  backend/middlewares/error-handler.js
  backend/package.json
  backend/prisma/migrations/20250610002910_fix_relationships_and_add_indexes/migration.sql
  backend/prisma/migrations/20250613051508_initial_setup/migration.sql
  backend/prisma/schema.prisma
  backend/routes/groups.js
Labels: 🐛 fix

#51 feat: 기록 랭킹 조회 API, 기록 상세 API 구현
  backend/app.js
  backend/controllers/records-view-controller.js
  backend/package-lock.json
  backend/package.json
  backend/prisma/migrations/20250613050551_init/migration.sql
  backend/routes/groups.js
  backend/routes/records.js
  backend/utils/db.js
  frontend/package-lock.json
  frontend/package.json
Labels: ✨ feat

#64 fix: group select에 discordWebhookUrl: true 추가,응답 데이터 가공에서 discordWebhookUrl의 값을 group.discordWebhookUrl로 변경
  backend/app.js
  backend/controllers/group-controller.js
  frontend/next.config.ts
Labels: 🐛 fix

#65 refactor: 운동 랭킹 조회 기능, 운동 기록 상세 조회 기능 리팩토링 & chore: 운동 기록 관련 오류 메시지 추가
  backend/controllers/records-view-controller.js
  backend/utils/const.js
Labels: 🧹 refactor, 🔧 chore

#73 feat: 그룹 참여 시 user 생성 로직 추가 / 참여 취소 시 취소 그룹에 한해 데이터 제거 / 비밀번호 해싱 처리
  backend/controllers/group-participant-controller.js
  backend/middlewares/validation-check.js
  backend/package-lock.json
  backend/package.json
  backend/prisma/migrations/20250613050551_init/migration.sql
  backend/prisma/migrations/20250613051508_initial_setup/migration.sql
  backend/prisma/migrations/20250618083733_init/migration.sql
  backend/prisma/schema.prisma
  backend/utils/const.js
  backend/utils/error.js
  backend/utils/password.js
Labels: ✨ feat

#90 [fix/upload] 그룹 컨트롤러 에러처리 수정
  backend/.gitignore
  backend/controllers/group-controller.js
Labels: 🐛 fix

#83 refactor: prisma로 데이터베이스 접근 방식 변경 및 에러 처리 개선
  backend/controllers/group-participant-controller.js
  backend/controllers/records-view-controller.js
  backend/middlewares/validation-check.js
  backend/routes/groups.js
  backend/utils/error.js
Labels: 🧹 refactor
